//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yandex.Alice.Sdk.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AliceResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AliceResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Yandex.Alice.Sdk.Resources.AliceResources", typeof(AliceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error_NoOAuthToken {
            get {
                return ResourceManager.GetString("Error_NoOAuthToken", resourceCulture);
            }
        }
        
        internal static string Error_NoSkillId {
            get {
                return ResourceManager.GetString("Error_NoSkillId", resourceCulture);
            }
        }
        
        internal static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        internal static string Error_TooLongString {
            get {
                return ResourceManager.GetString("Error_TooLongString", resourceCulture);
            }
        }
        
        internal static string Error_Unknown_Request_Type {
            get {
                return ResourceManager.GetString("Error_Unknown_Request_Type", resourceCulture);
            }
        }
        
        internal static string Error_NoDeviceId {
            get {
                return ResourceManager.GetString("Error_NoDeviceId", resourceCulture);
            }
        }
        
        internal static string Error_NoGroupId {
            get {
                return ResourceManager.GetString("Error_NoGroupId", resourceCulture);
            }
        }
        
        internal static string Error_NoScenarioId {
            get {
                return ResourceManager.GetString("Error_NoScenarioId", resourceCulture);
            }
        }
    }
}
