FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
ARG AliceSettings__SkillId
ENV AliceSettings__SkillId ${AliceSettings__SkillId}
ARG AliceSettings__DialogsOAuthToken
ENV AliceSettings__DialogsOAuthToken ${AliceSettings__DialogsOAuthToken}
ARG AliceSettings__IoTOAuthToken
ENV AliceSettings__IoTOAuthToken ${AliceSettings__IoTOAuthToken}
ARG AliceSettings__SmartHomeSkillId
ENV AliceSettings__SmartHomeSkillId ${AliceSettings__SmartHomeSkillId}
WORKDIR /build
COPY ./Yandex.Alice.Sdk.sln ./
COPY src/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p src/${file%.*}/ && mv $file src/${file%.*}/; done
COPY tests/*/*.csproj ./  
RUN for file in $(ls *.csproj); do mkdir -p tests/${file%.*}/ && mv $file tests/${file%.*}/; done
RUN dotnet restore Yandex.Alice.Sdk.sln
COPY . .
RUN dotnet test Yandex.Alice.Sdk.sln --no-restore

FROM build AS publish
WORKDIR "/build/src/Yandex.Alice.Sdk.Demo"
RUN dotnet publish "Yandex.Alice.Sdk.Demo.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Yandex.Alice.Sdk.Demo.dll"]