FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine
ARG AliceSettings__SkillId
ENV AliceSettings__SkillId ${AliceSettings__SkillId}
ARG AliceSettings__DialogsOAuthToken
ENV AliceSettings__DialogsOAuthToken ${AliceSettings__DialogsOAuthToken}
ARG AliceSettings__IoTOAuthToken
ENV AliceSettings__IoTOAuthToken ${AliceSettings__IoTOAuthToken}
ARG AliceSettings__SmartHomeSkillId
ENV AliceSettings__SmartHomeSkillId ${AliceSettings__SmartHomeSkillId}
ARG Nuget_Url=https://api.nuget.org/v3/index.json
ARG Nuget_Api_Key
WORKDIR /build
COPY ./Yandex.Alice.Sdk.sln ./
COPY src/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p src/${file%.*}/ && mv $file src/${file%.*}/; done
COPY tests/*/*.csproj ./  
RUN for file in $(ls *.csproj); do mkdir -p tests/${file%.*}/ && mv $file tests/${file%.*}/; done
RUN dotnet restore Yandex.Alice.Sdk.sln
COPY . .
RUN dotnet test Yandex.Alice.Sdk.sln --no-restore

RUN dotnet build ./src/Yandex.Alice.Sdk/*.csproj -c Release --no-restore
RUN dotnet pack ./src/Yandex.Alice.Sdk/*.csproj -c Release --include-symbols -p:SymbolPackageFormat=snupkg -o ./packages/

RUN dotnet nuget push ./packages/*.nupkg --source $Nuget_Url --api-key $Nuget_Api_Key --skip-duplicate
