name: yandex.alice.sdk

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-build
        push: false
        build-args: |
          AliceSettings__SkillId=${{ secrets.SKILL_SKILLID }}
          AliceSettings__DialogsOAuthToken=${{ secrets.DIALOGSAPI_DIALOGSOAUTHTOKEN }}
          AliceSettings__IoTOAuthToken=${{ secrets.ALICESETTINGS_IOTOAUTHTOKEN }}
          AliceSettings__SmartHomeSkillId=${{ secrets.ALICESETTINGS_SMARTHOMESKILLID }}
  push:
    needs: build
    environment:
      name: nuget
    name: Push NuGet package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Push NuGet
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile-nuget
        push: false
        build-args: |
          AliceSettings__SkillId=${{ secrets.SKILL_SKILLID }}
          AliceSettings__DialogsOAuthToken=${{ secrets.DIALOGSAPI_DIALOGSOAUTHTOKEN }}
          AliceSettings__IoTOAuthToken=${{ secrets.ALICESETTINGS_IOTOAUTHTOKEN }}
          AliceSettings__SmartHomeSkillId=${{ secrets.ALICESETTINGS_SMARTHOMESKILLID }}
          Nuget_Api_Key=${{ secrets.NUGET_API_KEY }}
    - name: Create new git tag
      run: bash ./scripts/create-tag.sh
